* Meu primeiro "Olá, mundo!" em COBOL

DIVISÃO DE IDENTIFICAÇÃO.
ID DO PROGRAMA. HELLOWORLD.
DIVISÃO DE DADOS.
SEÇÃO DE ARQUIVOS.
SEÇÃO DE ARMAZENAMENTO DE TRABALHO.
DIVISÃO DE PROCEDIMENTOS.
PROCEDIMENTO PRINCIPAL.
    MOSTRAR "Olá mundo".
    PARE CORRA.
FIM DO PROGRAMA HELLOWORLD.
